//Types for Login

//Types for Login
export const LOGIN_REQUEST_REQUEST = 'LOGIN_REQUEST_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

//Types for Sign up
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//Types for social Login
export const SOCIAL_LOGIN_REQUEST = 'SOCIAL_LOGIN_REQUEST';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAILURE = 'SOCIAL_LOGIN_FAILURE';

//Type for Forgot

export const FORGOT_REQUEST_REQUEST = 'FORGOT_REQUEST_REQUEST';
export const FORGOT_REQUEST_DIGITS = 'FORGOT_REQUEST_DIGITS';
export const FORGOT_PASSWORD_UPDATE_REQUEST = 'FORGOT_PASSWORD_UPDATE_REQUEST';

//Type for Businesses

export const GET_BUSINESS_REQUEST = 'GET_BUSINESS_REQUEST';
export const GET_BUSINESS_SUCCESS = 'GET_BUSINESS_SUCCESS';
export const GET_BUSINESS_FAILURE = 'GET_BUSINESS_FAILURE';

export const ADD_COMPANY_SERVICES_REQUEST = 'ADD_COMPANY_SERVICES_REQUEST';
export const ADD_COMPANY_SERVICES_SUCCESS = 'ADD_COMPANY_SERVICES_SUCCESS';
export const ADD_COMPANY_SERVICES_FAILURE = 'ADD_COMPANY_SERVICES_FAILURE';

export const BUSINESS_DETAILS_REQUEST = 'BUSINESS_DETAILS_REQUEST';
export const BUSINESS_DETAILS_SUCCESS = 'BUSINESS_DETAILS_SUCCESS';
export const BUSINESS_DETAILS_FAILURE = 'BUSINESS_DETAILS_FAILURE';

// Add/Get experiences
export const ADD_EXP_REQUEST = 'ADD_EXP_REQUEST';
export const ADD_EXP_SUCCESS = 'ADD_EXP_SUCCESS';
export const ADD_EXP_FAILURE = 'ADD_EXP_FAILURE';

export const GET_EXP_REQUEST = 'GET_EXP_REQUEST';
export const GET_EXP_SUCCESS = 'GET_EXP_SUCCESS';
export const GET_EXP_FAILURE = 'GET_EXP_FAILURE';

// Add/Get workers
export const ADD_WORKER_REQUEST = 'ADD_WORKER_REQUEST';
export const ADD_WORKER_SUCCESS = 'ADD_WORKER_SUCCESS';
export const ADD_WORKER_FAILURE = 'ADD_WORKER_FAILURE';

export const GET_WORKERS_REQUEST = 'GET_WORKERS_REQUEST';
export const GET_WORKERS_SUCCESS = 'GET_WORKERS_SUCCESS';
export const GET_WORKERS_FAILURE = 'GET_WORKERS_FAILURE';

// Add/Get Reviews
export const GET_REVIEW_REQUEST = 'GET_REVIEW_REQUEST';
export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS';
export const GET_REVIEW_FAILURE = 'GET_REVIEW_FAILURE';

export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_REVIEW_FAILURE';

// Add/Get Service Reviews
export const GET_SERVICE_REVIEW_REQUEST = 'GET_SERVICE_REVIEW_REQUEST';
export const GET_SERVICE_REVIEW_SUCCESS = 'GET_SERVICE_REVIEW_SUCCESS';
export const GET_SERVICE_REVIEW_FAILURE = 'GET_SERVICE_REVIEW_FAILURE';

export const ADD_SERVICE_REVIEW_REQUEST = 'ADD_SERVICE_REVIEW_REQUEST';
export const ADD_SERVICE_REVIEW_SUCCESS = 'ADD_SERVICE_REVIEW_SUCCESS';
export const ADD_SERVICE_REVIEW_FAILURE = 'ADD_SERVICE_REVIEW_FAILURE';
// for error get country codes
export const GET_COUNTRY_REQUEST = 'GET_COUNTRY_REQUEST';
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS';
export const GET_COUNTRY_FAILURE = 'GET_COUNTRY_FAILURE';

export const VERIFYUSER_REQUEST = 'VERIFYUSER_REQUEST';
export const VERIFYUSER_SUCCESS = 'VERIFYUSER_SUCCESS';
export const VERIFYUSER_FAILURE = 'VERIFYUSER_FAILURE';

export const RESENDOTPCODE_REQUEST = 'RESENDOTPCODE_REQUEST';
export const RESENDOTPCODE_SUCCESS = 'RESENDOTPCODE_SUCCESS';
export const RESENDOTPCODE_FAILURE = 'RESENDOTPCODE_FAILURE';

export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILURE = 'RESET_FAILURE';

export const NEWPASSWORD_REQUEST = 'NEWPASSWORD_REQUEST';
export const NEWPASSWORD_SUCCESS = 'NEWPASSWORD_SUCCESS';
export const NEWPASSWORD_FAILURE = 'NEWPASSWORD_FAILURE';

export const CONFIRMRESETPASSWORD_REQUEST = 'CONFIRMRESETPASSWORD_REQUEST';
export const CONFIRMRESETPASSWORD_SUCCESS = 'CONFIRMRESETPASSWORD_SUCCESS';
export const CONFIRMRESETPASSWORD_FAILURE = 'CONFIRMRESETPASSWORD_FAILURE';

// for error msgs
export const ERRORMSG_REQUEST = 'ERRORMSG_REQUEST';
export const ERRORMSG_SUCCESS = 'ERRORMSG_SUCCESS';

export const GET_IWASHERE_REQUEST = 'GET_IWASHERE_REQUEST';
export const GET_IWASHERE_SUCCESS = 'GET_IWASHERE_SUCCESS';
export const GET_IWASHERE_FAILURE = 'GET_IWASHERE_FAILURE';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const GET_RATING_REQUEST = 'GET_RATING_REQUEST';
export const GET_RATING_SUCCESS = 'GET_RATING_SUCCESS';
export const GET_RATING_FAILURE = 'GET_RATING_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const REGISTER_COMPANY_REQUEST = 'REGISTER_COMPANY_REQUEST';
export const REGISTER_COMPANY_SUCCESS = 'REGISTER_COMPANY_SUCCESS';
export const REGISTER_COMPANY_FAILURE = 'REGISTER_COMPANY_FAILURE';

export const GET_USER_COMPANY_REQUEST = 'GET_USER_COMPANY_REQUEST';
export const GET_USER_COMPANY_SUCCESS = 'GET_USER_COMPANY_SUCCESS';
export const GET_USER_COMPANY_FAILURE = 'GET_USER_COMPANY_FAILURE';

export const UPDATE_COMPANY_REQUEST = 'UPDATE_COMPANY_REQUEST';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_FAILURE = 'UPDATE_COMPANY_FAILURE';

export const GET_SETTINGS_REQUEST = 'GET_SETTINGS_REQUEST';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const GET_SETTINGS_FAILURE = 'GET_SETTINGS_FAILURE';

export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE';